1.1
YunoHost-Apps/garradin_ynh pull request #52
Opened 2021-05-07 17:30 UTC by rodinux

## Problem
- *Upgrade to version 1.1.4*
-  *Add php surry repository  extra dependencies*

## Solution
- *I try use some scripts used before in old nextcloud commits and adapt them*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ x ] Upgrade from last version tested.
- [ x ] Can be reviewed and tested.

2021-05-07 17:39 UTC, rodinux commented
!testme

2021-05-07 18:49 UTC, rodinux commented
update to new versions 1.1 with php7.4... but I have some doubt about the scripts... on a personal server I can't change the domain url...

2021-05-10 14:27 UTC, ericgaspar requested changes
You can leave the equal sign.

2021-05-10 14:27 UTC, ericgaspar commented on scripts/install
> +  ynh_permission_update --permission "main" --add "visitors"
```suggestion
  ynh_permission_update --permission="main" --add="visitors"
```

2021-05-10 14:54 UTC, rodinux commented on README_fr.md
> +[![Niveau d'intégration](https://dash.yunohost.org/integration/garradin.svg)](https://dash.yunohost.org/appci/app/garradin) ![](https://ci-apps.yunohost.org/ci/badges/garradin.status.svg) ![](https:/
Ok

2021-05-10 14:55 UTC, rodinux commented
!testme

2021-05-10 15:31 UTC, rodinux commented
!testme

2021-05-10 18:04 UTC, merged